/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[..catchAll]': RouteRecordInfo<
      '/[..catchAll]',
      '/:atchAll(.*)',
      { atchAll: ParamValue<true> },
      { atchAll: ParamValue<false> },
      | never
    >,
    '/decks/': RouteRecordInfo<
      '/decks/',
      '/decks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/decks/[slug]/': RouteRecordInfo<
      '/decks/[slug]/',
      '/decks/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/decks/[slug]/edit': RouteRecordInfo<
      '/decks/[slug]/edit',
      '/decks/:slug/edit',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/decks/create/': RouteRecordInfo<
      '/decks/create/',
      '/decks/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practice/[slug]': RouteRecordInfo<
      '/practice/[slug]',
      '/practice/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[..catchAll].vue': {
      routes:
        | '/[..catchAll]'
      views:
        | never
    }
    'src/pages/decks/index.vue': {
      routes:
        | '/decks/'
      views:
        | never
    }
    'src/pages/decks/[slug]/index.vue': {
      routes:
        | '/decks/[slug]/'
      views:
        | never
    }
    'src/pages/decks/[slug]/edit.vue': {
      routes:
        | '/decks/[slug]/edit'
      views:
        | never
    }
    'src/pages/decks/create/index.vue': {
      routes:
        | '/decks/create/'
      views:
        | never
    }
    'src/pages/practice/[slug].vue': {
      routes:
        | '/practice/[slug]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
